version: '3.8'

services:
  project2:
    image: ankitsinghpawar/project2:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project2
    ports:
      - "8088:80"
    networks:
      - project2_app-network
    restart: always
    environment:
      - SERVER_PORT=8086
      - SPRING_PROFILES_ACTIVE=prod

networks:
  project2_app-network:
    driver: bridge
